// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD_suuKlWWK1NMNbb6E34bh1Lopz6CSsm8',
    appId: '1:1086280242740:web:81b3e4d206cdef79349c61',
    messagingSenderId: '1086280242740',
    projectId: 'flutter-todo-realtime-5a0ea',
    authDomain: 'flutter-todo-realtime-5a0ea.firebaseapp.com',
    storageBucket: 'flutter-todo-realtime-5a0ea.firebasestorage.app',
    measurementId: 'G-LDJ1KMLSTK',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAHAJcLGBM1Fb8tiFZH2s9pxumVMHTRSmk',
    appId: '1:1086280242740:android:f2c88f9bcf95b5b1349c61',
    messagingSenderId: '1086280242740',
    projectId: 'flutter-todo-realtime-5a0ea',
    storageBucket: 'flutter-todo-realtime-5a0ea.firebasestorage.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBJ3c62mB9eCL68fWkg_cbO-gTR4zQ2DME',
    appId: '1:1086280242740:ios:8c8af3b36aa66772349c61',
    messagingSenderId: '1086280242740',
    projectId: 'flutter-todo-realtime-5a0ea',
    storageBucket: 'flutter-todo-realtime-5a0ea.firebasestorage.app',
    iosBundleId: 'com.example.flutterTodoRealtime',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD_suuKlWWK1NMNbb6E34bh1Lopz6CSsm8',
    appId: '1:1086280242740:web:70535b316417f25e349c61',
    messagingSenderId: '1086280242740',
    projectId: 'flutter-todo-realtime-5a0ea',
    authDomain: 'flutter-todo-realtime-5a0ea.firebaseapp.com',
    storageBucket: 'flutter-todo-realtime-5a0ea.firebasestorage.app',
    measurementId: 'G-TLDYSLGP83',
  );
}
